/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.InputParameter;
import org.openapitools.client.model.JsonSchema;
import org.openapitools.client.model.ResultMetadata;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Action
 */
public class ActionTest {
    private final Action model = new Action();

    /**
     * Model tests for Action
     */
    @Test
    public void testAction() {
        // TODO: test Action
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'inputJsonSchema'
     */
    @Test
    public void inputJsonSchemaTest() {
        // TODO: test inputJsonSchema
    }

    /**
     * Test the property 'inputParameters'
     */
    @Test
    public void inputParametersTest() {
        // TODO: test inputParameters
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'resultJsonSchema'
     */
    @Test
    public void resultJsonSchemaTest() {
        // TODO: test resultJsonSchema
    }

    /**
     * Test the property 'resultMetadata'
     */
    @Test
    public void resultMetadataTest() {
        // TODO: test resultMetadata
    }

}
