/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AccessCredentials;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExchangeAuthCodeResponse
 */
public class ExchangeAuthCodeResponseTest {
    private final ExchangeAuthCodeResponse model = new ExchangeAuthCodeResponse();

    /**
     * Model tests for ExchangeAuthCodeResponse
     */
    @Test
    public void testExchangeAuthCodeResponse() {
        // TODO: test ExchangeAuthCodeResponse
    }

    /**
     * Test the property 'accessCredentials'
     */
    @Test
    public void accessCredentialsTest() {
        // TODO: test accessCredentials
    }

}
