/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.MaintenanceSchedule;
import org.openapitools.client.model.MaintenanceSettings;
import org.openapitools.client.model.NotificationParameter;
import org.openapitools.client.model.ProvisionedResource;
import org.openapitools.client.model.SloMetadata;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Instance
 */
public class InstanceTest {
    private final Instance model = new Instance();

    /**
     * Model tests for Instance
     */
    @Test
    public void testInstance() {
        // TODO: test Instance
    }

    /**
     * Test the property 'consumerDefinedName'
     */
    @Test
    public void consumerDefinedNameTest() {
        // TODO: test consumerDefinedName
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'instanceType'
     */
    @Test
    public void instanceTypeTest() {
        // TODO: test instanceType
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'maintenancePolicyNames'
     */
    @Test
    public void maintenancePolicyNamesTest() {
        // TODO: test maintenancePolicyNames
    }

    /**
     * Test the property 'maintenanceSchedules'
     */
    @Test
    public void maintenanceSchedulesTest() {
        // TODO: test maintenanceSchedules
    }

    /**
     * Test the property 'maintenanceSettings'
     */
    @Test
    public void maintenanceSettingsTest() {
        // TODO: test maintenanceSettings
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'notificationParameters'
     */
    @Test
    public void notificationParametersTest() {
        // TODO: test notificationParameters
    }

    /**
     * Test the property 'producerMetadata'
     */
    @Test
    public void producerMetadataTest() {
        // TODO: test producerMetadata
    }

    /**
     * Test the property 'provisionedResources'
     */
    @Test
    public void provisionedResourcesTest() {
        // TODO: test provisionedResources
    }

    /**
     * Test the property 'slmInstanceTemplate'
     */
    @Test
    public void slmInstanceTemplateTest() {
        // TODO: test slmInstanceTemplate
    }

    /**
     * Test the property 'sloMetadata'
     */
    @Test
    public void sloMetadataTest() {
        // TODO: test sloMetadata
    }

    /**
     * Test the property 'softwareVersions'
     */
    @Test
    public void softwareVersionsTest() {
        // TODO: test softwareVersions
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'tenantProjectId'
     */
    @Test
    public void tenantProjectIdTest() {
        // TODO: test tenantProjectId
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

}
