/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EntityType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListEntityTypesResponse
 */
public class ListEntityTypesResponseTest {
    private final ListEntityTypesResponse model = new ListEntityTypesResponse();

    /**
     * Model tests for ListEntityTypesResponse
     */
    @Test
    public void testListEntityTypesResponse() {
        // TODO: test ListEntityTypesResponse
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

    /**
     * Test the property 'types'
     */
    @Test
    public void typesTest() {
        // TODO: test types
    }

    /**
     * Test the property 'unsupportedTypeNames'
     */
    @Test
    public void unsupportedTypeNamesTest() {
        // TODO: test unsupportedTypeNames
    }

}
