/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MaintenanceSchedule
 */
public class MaintenanceScheduleTest {
    private final MaintenanceSchedule model = new MaintenanceSchedule();

    /**
     * Model tests for MaintenanceSchedule
     */
    @Test
    public void testMaintenanceSchedule() {
        // TODO: test MaintenanceSchedule
    }

    /**
     * Test the property 'canReschedule'
     */
    @Test
    public void canRescheduleTest() {
        // TODO: test canReschedule
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'rolloutManagementPolicy'
     */
    @Test
    public void rolloutManagementPolicyTest() {
        // TODO: test rolloutManagementPolicy
    }

    /**
     * Test the property 'scheduleDeadlineTime'
     */
    @Test
    public void scheduleDeadlineTimeTest() {
        // TODO: test scheduleDeadlineTime
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

}
