/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateEntitiesWithConditionsResponse
 */
public class UpdateEntitiesWithConditionsResponseTest {
    private final UpdateEntitiesWithConditionsResponse model = new UpdateEntitiesWithConditionsResponse();

    /**
     * Model tests for UpdateEntitiesWithConditionsResponse
     */
    @Test
    public void testUpdateEntitiesWithConditionsResponse() {
        // TODO: test UpdateEntitiesWithConditionsResponse
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

}
