/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.InputParameter;
import org.openapitools.client.model.JsonSchema;
import org.openapitools.client.model.ResultMetadata;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Action message contains metadata information about a single action present in the external system.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:56:10.672855+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class Action {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  @javax.annotation.Nullable
  private String displayName;

  public static final String SERIALIZED_NAME_INPUT_JSON_SCHEMA = "inputJsonSchema";
  @SerializedName(SERIALIZED_NAME_INPUT_JSON_SCHEMA)
  @javax.annotation.Nullable
  private JsonSchema inputJsonSchema;

  public static final String SERIALIZED_NAME_INPUT_PARAMETERS = "inputParameters";
  @SerializedName(SERIALIZED_NAME_INPUT_PARAMETERS)
  @javax.annotation.Nullable
  private List<InputParameter> inputParameters = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_RESULT_JSON_SCHEMA = "resultJsonSchema";
  @SerializedName(SERIALIZED_NAME_RESULT_JSON_SCHEMA)
  @javax.annotation.Nullable
  private JsonSchema resultJsonSchema;

  public static final String SERIALIZED_NAME_RESULT_METADATA = "resultMetadata";
  @SerializedName(SERIALIZED_NAME_RESULT_METADATA)
  @javax.annotation.Nullable
  private List<ResultMetadata> resultMetadata = new ArrayList<>();

  public Action() {
  }

  public Action description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Brief Description of action
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public Action displayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Display Name of action to be shown on client side
   * @return displayName
   */
  @javax.annotation.Nullable
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  public Action inputJsonSchema(@javax.annotation.Nullable JsonSchema inputJsonSchema) {
    this.inputJsonSchema = inputJsonSchema;
    return this;
  }

  /**
   * Get inputJsonSchema
   * @return inputJsonSchema
   */
  @javax.annotation.Nullable
  public JsonSchema getInputJsonSchema() {
    return inputJsonSchema;
  }

  public void setInputJsonSchema(@javax.annotation.Nullable JsonSchema inputJsonSchema) {
    this.inputJsonSchema = inputJsonSchema;
  }


  public Action inputParameters(@javax.annotation.Nullable List<InputParameter> inputParameters) {
    this.inputParameters = inputParameters;
    return this;
  }

  public Action addInputParametersItem(InputParameter inputParametersItem) {
    if (this.inputParameters == null) {
      this.inputParameters = new ArrayList<>();
    }
    this.inputParameters.add(inputParametersItem);
    return this;
  }

  /**
   * List containing input parameter metadata.
   * @return inputParameters
   */
  @javax.annotation.Nullable
  public List<InputParameter> getInputParameters() {
    return inputParameters;
  }

  public void setInputParameters(@javax.annotation.Nullable List<InputParameter> inputParameters) {
    this.inputParameters = inputParameters;
  }


  public Action name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the action.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Action resultJsonSchema(@javax.annotation.Nullable JsonSchema resultJsonSchema) {
    this.resultJsonSchema = resultJsonSchema;
    return this;
  }

  /**
   * Get resultJsonSchema
   * @return resultJsonSchema
   */
  @javax.annotation.Nullable
  public JsonSchema getResultJsonSchema() {
    return resultJsonSchema;
  }

  public void setResultJsonSchema(@javax.annotation.Nullable JsonSchema resultJsonSchema) {
    this.resultJsonSchema = resultJsonSchema;
  }


  public Action resultMetadata(@javax.annotation.Nullable List<ResultMetadata> resultMetadata) {
    this.resultMetadata = resultMetadata;
    return this;
  }

  public Action addResultMetadataItem(ResultMetadata resultMetadataItem) {
    if (this.resultMetadata == null) {
      this.resultMetadata = new ArrayList<>();
    }
    this.resultMetadata.add(resultMetadataItem);
    return this;
  }

  /**
   * List containing the metadata of result fields.
   * @return resultMetadata
   */
  @javax.annotation.Nullable
  public List<ResultMetadata> getResultMetadata() {
    return resultMetadata;
  }

  public void setResultMetadata(@javax.annotation.Nullable List<ResultMetadata> resultMetadata) {
    this.resultMetadata = resultMetadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Action action = (Action) o;
    return Objects.equals(this.description, action.description) &&
        Objects.equals(this.displayName, action.displayName) &&
        Objects.equals(this.inputJsonSchema, action.inputJsonSchema) &&
        Objects.equals(this.inputParameters, action.inputParameters) &&
        Objects.equals(this.name, action.name) &&
        Objects.equals(this.resultJsonSchema, action.resultJsonSchema) &&
        Objects.equals(this.resultMetadata, action.resultMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, displayName, inputJsonSchema, inputParameters, name, resultJsonSchema, resultMetadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Action {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    inputJsonSchema: ").append(toIndentedString(inputJsonSchema)).append("\n");
    sb.append("    inputParameters: ").append(toIndentedString(inputParameters)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    resultJsonSchema: ").append(toIndentedString(resultJsonSchema)).append("\n");
    sb.append("    resultMetadata: ").append(toIndentedString(resultMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("description", "displayName", "inputJsonSchema", "inputParameters", "name", "resultJsonSchema", "resultMetadata"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Action
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Action.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Action is not found in the empty JSON string", Action.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Action.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Action` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      // validate the optional field `inputJsonSchema`
      if (jsonObj.get("inputJsonSchema") != null && !jsonObj.get("inputJsonSchema").isJsonNull()) {
        JsonSchema.validateJsonElement(jsonObj.get("inputJsonSchema"));
      }
      if (jsonObj.get("inputParameters") != null && !jsonObj.get("inputParameters").isJsonNull()) {
        JsonArray jsonArrayinputParameters = jsonObj.getAsJsonArray("inputParameters");
        if (jsonArrayinputParameters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("inputParameters").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `inputParameters` to be an array in the JSON string but got `%s`", jsonObj.get("inputParameters").toString()));
          }

          // validate the optional field `inputParameters` (array)
          for (int i = 0; i < jsonArrayinputParameters.size(); i++) {
            InputParameter.validateJsonElement(jsonArrayinputParameters.get(i));
          };
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `resultJsonSchema`
      if (jsonObj.get("resultJsonSchema") != null && !jsonObj.get("resultJsonSchema").isJsonNull()) {
        JsonSchema.validateJsonElement(jsonObj.get("resultJsonSchema"));
      }
      if (jsonObj.get("resultMetadata") != null && !jsonObj.get("resultMetadata").isJsonNull()) {
        JsonArray jsonArrayresultMetadata = jsonObj.getAsJsonArray("resultMetadata");
        if (jsonArrayresultMetadata != null) {
          // ensure the json data is an array
          if (!jsonObj.get("resultMetadata").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `resultMetadata` to be an array in the JSON string but got `%s`", jsonObj.get("resultMetadata").toString()));
          }

          // validate the optional field `resultMetadata` (array)
          for (int i = 0; i < jsonArrayresultMetadata.size(); i++) {
            ResultMetadata.validateJsonElement(jsonArrayresultMetadata.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Action.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Action' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Action> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Action.class));

       return (TypeAdapter<T>) new TypeAdapter<Action>() {
           @Override
           public void write(JsonWriter out, Action value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Action read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Action given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Action
   * @throws IOException if the JSON string is invalid with respect to Action
   */
  public static Action fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Action.class);
  }

  /**
   * Convert an instance of Action to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

