/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AccessCredentials;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ExchangeAuthCodeResponse includes the returned access token and its associated credentials.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:56:10.672855+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ExchangeAuthCodeResponse {
  public static final String SERIALIZED_NAME_ACCESS_CREDENTIALS = "accessCredentials";
  @SerializedName(SERIALIZED_NAME_ACCESS_CREDENTIALS)
  @javax.annotation.Nullable
  private AccessCredentials accessCredentials;

  public ExchangeAuthCodeResponse() {
  }

  public ExchangeAuthCodeResponse accessCredentials(@javax.annotation.Nullable AccessCredentials accessCredentials) {
    this.accessCredentials = accessCredentials;
    return this;
  }

  /**
   * Get accessCredentials
   * @return accessCredentials
   */
  @javax.annotation.Nullable
  public AccessCredentials getAccessCredentials() {
    return accessCredentials;
  }

  public void setAccessCredentials(@javax.annotation.Nullable AccessCredentials accessCredentials) {
    this.accessCredentials = accessCredentials;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExchangeAuthCodeResponse exchangeAuthCodeResponse = (ExchangeAuthCodeResponse) o;
    return Objects.equals(this.accessCredentials, exchangeAuthCodeResponse.accessCredentials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessCredentials);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExchangeAuthCodeResponse {\n");
    sb.append("    accessCredentials: ").append(toIndentedString(accessCredentials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("accessCredentials"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ExchangeAuthCodeResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExchangeAuthCodeResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExchangeAuthCodeResponse is not found in the empty JSON string", ExchangeAuthCodeResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExchangeAuthCodeResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExchangeAuthCodeResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `accessCredentials`
      if (jsonObj.get("accessCredentials") != null && !jsonObj.get("accessCredentials").isJsonNull()) {
        AccessCredentials.validateJsonElement(jsonObj.get("accessCredentials"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExchangeAuthCodeResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExchangeAuthCodeResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExchangeAuthCodeResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExchangeAuthCodeResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ExchangeAuthCodeResponse>() {
           @Override
           public void write(JsonWriter out, ExchangeAuthCodeResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExchangeAuthCodeResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ExchangeAuthCodeResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ExchangeAuthCodeResponse
   * @throws IOException if the JSON string is invalid with respect to ExchangeAuthCodeResponse
   */
  public static ExchangeAuthCodeResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExchangeAuthCodeResponse.class);
  }

  /**
   * Convert an instance of ExchangeAuthCodeResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

