/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EntityType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Response message for EntityService.ListEntityTypes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:56:10.672855+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ListEntityTypesResponse {
  public static final String SERIALIZED_NAME_NEXT_PAGE_TOKEN = "nextPageToken";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE_TOKEN)
  @javax.annotation.Nullable
  private String nextPageToken;

  public static final String SERIALIZED_NAME_TYPES = "types";
  @SerializedName(SERIALIZED_NAME_TYPES)
  @javax.annotation.Nullable
  private List<EntityType> types = new ArrayList<>();

  public static final String SERIALIZED_NAME_UNSUPPORTED_TYPE_NAMES = "unsupportedTypeNames";
  @SerializedName(SERIALIZED_NAME_UNSUPPORTED_TYPE_NAMES)
  @javax.annotation.Nullable
  private List<String> unsupportedTypeNames = new ArrayList<>();

  public ListEntityTypesResponse() {
  }

  public ListEntityTypesResponse nextPageToken(@javax.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  /**
   * Next page token if more entity types available.
   * @return nextPageToken
   */
  @javax.annotation.Nullable
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(@javax.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  public ListEntityTypesResponse types(@javax.annotation.Nullable List<EntityType> types) {
    this.types = types;
    return this;
  }

  public ListEntityTypesResponse addTypesItem(EntityType typesItem) {
    if (this.types == null) {
      this.types = new ArrayList<>();
    }
    this.types.add(typesItem);
    return this;
  }

  /**
   * List of metadata related to all entity types.
   * @return types
   */
  @javax.annotation.Nullable
  public List<EntityType> getTypes() {
    return types;
  }

  public void setTypes(@javax.annotation.Nullable List<EntityType> types) {
    this.types = types;
  }


  public ListEntityTypesResponse unsupportedTypeNames(@javax.annotation.Nullable List<String> unsupportedTypeNames) {
    this.unsupportedTypeNames = unsupportedTypeNames;
    return this;
  }

  public ListEntityTypesResponse addUnsupportedTypeNamesItem(String unsupportedTypeNamesItem) {
    if (this.unsupportedTypeNames == null) {
      this.unsupportedTypeNames = new ArrayList<>();
    }
    this.unsupportedTypeNames.add(unsupportedTypeNamesItem);
    return this;
  }

  /**
   * List of entity type names which contain unsupported Datatypes. Check datatype.proto for more information.
   * @return unsupportedTypeNames
   */
  @javax.annotation.Nullable
  public List<String> getUnsupportedTypeNames() {
    return unsupportedTypeNames;
  }

  public void setUnsupportedTypeNames(@javax.annotation.Nullable List<String> unsupportedTypeNames) {
    this.unsupportedTypeNames = unsupportedTypeNames;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListEntityTypesResponse listEntityTypesResponse = (ListEntityTypesResponse) o;
    return Objects.equals(this.nextPageToken, listEntityTypesResponse.nextPageToken) &&
        Objects.equals(this.types, listEntityTypesResponse.types) &&
        Objects.equals(this.unsupportedTypeNames, listEntityTypesResponse.unsupportedTypeNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextPageToken, types, unsupportedTypeNames);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListEntityTypesResponse {\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    unsupportedTypeNames: ").append(toIndentedString(unsupportedTypeNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("nextPageToken", "types", "unsupportedTypeNames"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListEntityTypesResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListEntityTypesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListEntityTypesResponse is not found in the empty JSON string", ListEntityTypesResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListEntityTypesResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListEntityTypesResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nextPageToken") != null && !jsonObj.get("nextPageToken").isJsonNull()) && !jsonObj.get("nextPageToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextPageToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextPageToken").toString()));
      }
      if (jsonObj.get("types") != null && !jsonObj.get("types").isJsonNull()) {
        JsonArray jsonArraytypes = jsonObj.getAsJsonArray("types");
        if (jsonArraytypes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("types").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `types` to be an array in the JSON string but got `%s`", jsonObj.get("types").toString()));
          }

          // validate the optional field `types` (array)
          for (int i = 0; i < jsonArraytypes.size(); i++) {
            EntityType.validateJsonElement(jsonArraytypes.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("unsupportedTypeNames") != null && !jsonObj.get("unsupportedTypeNames").isJsonNull() && !jsonObj.get("unsupportedTypeNames").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `unsupportedTypeNames` to be an array in the JSON string but got `%s`", jsonObj.get("unsupportedTypeNames").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListEntityTypesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListEntityTypesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListEntityTypesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListEntityTypesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ListEntityTypesResponse>() {
           @Override
           public void write(JsonWriter out, ListEntityTypesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListEntityTypesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListEntityTypesResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListEntityTypesResponse
   * @throws IOException if the JSON string is invalid with respect to ListEntityTypesResponse
   */
  public static ListEntityTypesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListEntityTypesResponse.class);
  }

  /**
   * Convert an instance of ListEntityTypesResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

