/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Maintenance schedule which is exposed to customer and potentially end user, indicating published upcoming future maintenance schedule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:56:10.672855+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class MaintenanceSchedule {
  public static final String SERIALIZED_NAME_CAN_RESCHEDULE = "canReschedule";
  @Deprecated
  @SerializedName(SERIALIZED_NAME_CAN_RESCHEDULE)
  @javax.annotation.Nullable
  private Boolean canReschedule;

  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  @javax.annotation.Nullable
  private String endTime;

  public static final String SERIALIZED_NAME_ROLLOUT_MANAGEMENT_POLICY = "rolloutManagementPolicy";
  @SerializedName(SERIALIZED_NAME_ROLLOUT_MANAGEMENT_POLICY)
  @javax.annotation.Nullable
  private String rolloutManagementPolicy;

  public static final String SERIALIZED_NAME_SCHEDULE_DEADLINE_TIME = "scheduleDeadlineTime";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_DEADLINE_TIME)
  @javax.annotation.Nullable
  private String scheduleDeadlineTime;

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  @javax.annotation.Nullable
  private String startTime;

  public MaintenanceSchedule() {
  }

  @Deprecated
  public MaintenanceSchedule canReschedule(@javax.annotation.Nullable Boolean canReschedule) {
    this.canReschedule = canReschedule;
    return this;
  }

  /**
   * This field is deprecated, and will be always set to true since reschedule can happen multiple times now. This field should not be removed until all service producers remove this for their customers.
   * @return canReschedule
   * @deprecated
   */
  @Deprecated
  @javax.annotation.Nullable
  public Boolean getCanReschedule() {
    return canReschedule;
  }

  @Deprecated
  public void setCanReschedule(@javax.annotation.Nullable Boolean canReschedule) {
    this.canReschedule = canReschedule;
  }


  public MaintenanceSchedule endTime(@javax.annotation.Nullable String endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * The scheduled end time for the maintenance.
   * @return endTime
   */
  @javax.annotation.Nullable
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(@javax.annotation.Nullable String endTime) {
    this.endTime = endTime;
  }


  public MaintenanceSchedule rolloutManagementPolicy(@javax.annotation.Nullable String rolloutManagementPolicy) {
    this.rolloutManagementPolicy = rolloutManagementPolicy;
    return this;
  }

  /**
   * The rollout management policy this maintenance schedule is associated with. When doing reschedule update request, the reschedule should be against this given policy.
   * @return rolloutManagementPolicy
   */
  @javax.annotation.Nullable
  public String getRolloutManagementPolicy() {
    return rolloutManagementPolicy;
  }

  public void setRolloutManagementPolicy(@javax.annotation.Nullable String rolloutManagementPolicy) {
    this.rolloutManagementPolicy = rolloutManagementPolicy;
  }


  public MaintenanceSchedule scheduleDeadlineTime(@javax.annotation.Nullable String scheduleDeadlineTime) {
    this.scheduleDeadlineTime = scheduleDeadlineTime;
    return this;
  }

  /**
   * schedule_deadline_time is the time deadline any schedule start time cannot go beyond, including reschedule. It&#39;s normally the initial schedule start time plus maintenance window length (1 day or 1 week). Maintenance cannot be scheduled to start beyond this deadline.
   * @return scheduleDeadlineTime
   */
  @javax.annotation.Nullable
  public String getScheduleDeadlineTime() {
    return scheduleDeadlineTime;
  }

  public void setScheduleDeadlineTime(@javax.annotation.Nullable String scheduleDeadlineTime) {
    this.scheduleDeadlineTime = scheduleDeadlineTime;
  }


  public MaintenanceSchedule startTime(@javax.annotation.Nullable String startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * The scheduled start time for the maintenance.
   * @return startTime
   */
  @javax.annotation.Nullable
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(@javax.annotation.Nullable String startTime) {
    this.startTime = startTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceSchedule maintenanceSchedule = (MaintenanceSchedule) o;
    return Objects.equals(this.canReschedule, maintenanceSchedule.canReschedule) &&
        Objects.equals(this.endTime, maintenanceSchedule.endTime) &&
        Objects.equals(this.rolloutManagementPolicy, maintenanceSchedule.rolloutManagementPolicy) &&
        Objects.equals(this.scheduleDeadlineTime, maintenanceSchedule.scheduleDeadlineTime) &&
        Objects.equals(this.startTime, maintenanceSchedule.startTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canReschedule, endTime, rolloutManagementPolicy, scheduleDeadlineTime, startTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceSchedule {\n");
    sb.append("    canReschedule: ").append(toIndentedString(canReschedule)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    rolloutManagementPolicy: ").append(toIndentedString(rolloutManagementPolicy)).append("\n");
    sb.append("    scheduleDeadlineTime: ").append(toIndentedString(scheduleDeadlineTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("canReschedule", "endTime", "rolloutManagementPolicy", "scheduleDeadlineTime", "startTime"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MaintenanceSchedule
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MaintenanceSchedule.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MaintenanceSchedule is not found in the empty JSON string", MaintenanceSchedule.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MaintenanceSchedule.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MaintenanceSchedule` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("endTime") != null && !jsonObj.get("endTime").isJsonNull()) && !jsonObj.get("endTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endTime").toString()));
      }
      if ((jsonObj.get("rolloutManagementPolicy") != null && !jsonObj.get("rolloutManagementPolicy").isJsonNull()) && !jsonObj.get("rolloutManagementPolicy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rolloutManagementPolicy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rolloutManagementPolicy").toString()));
      }
      if ((jsonObj.get("scheduleDeadlineTime") != null && !jsonObj.get("scheduleDeadlineTime").isJsonNull()) && !jsonObj.get("scheduleDeadlineTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `scheduleDeadlineTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scheduleDeadlineTime").toString()));
      }
      if ((jsonObj.get("startTime") != null && !jsonObj.get("startTime").isJsonNull()) && !jsonObj.get("startTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `startTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startTime").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MaintenanceSchedule.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MaintenanceSchedule' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MaintenanceSchedule> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MaintenanceSchedule.class));

       return (TypeAdapter<T>) new TypeAdapter<MaintenanceSchedule>() {
           @Override
           public void write(JsonWriter out, MaintenanceSchedule value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MaintenanceSchedule read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MaintenanceSchedule given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MaintenanceSchedule
   * @throws IOException if the JSON string is invalid with respect to MaintenanceSchedule
   */
  public static MaintenanceSchedule fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MaintenanceSchedule.class);
  }

  /**
   * Convert an instance of MaintenanceSchedule to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

