/*
 * Connectors API
 * Enables users to create and manage connections to Google Cloud services and third-party business applications using the Connectors interface.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.SloEligibility;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PerSliSloEligibility is a mapping from an SLI name to eligibility.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T14:56:10.672855+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class PerSliSloEligibility {
  public static final String SERIALIZED_NAME_ELIGIBILITIES = "eligibilities";
  @SerializedName(SERIALIZED_NAME_ELIGIBILITIES)
  @javax.annotation.Nullable
  private Map<String, SloEligibility> eligibilities = new HashMap<>();

  public PerSliSloEligibility() {
  }

  public PerSliSloEligibility eligibilities(@javax.annotation.Nullable Map<String, SloEligibility> eligibilities) {
    this.eligibilities = eligibilities;
    return this;
  }

  public PerSliSloEligibility putEligibilitiesItem(String key, SloEligibility eligibilitiesItem) {
    if (this.eligibilities == null) {
      this.eligibilities = new HashMap<>();
    }
    this.eligibilities.put(key, eligibilitiesItem);
    return this;
  }

  /**
   * An entry in the eligibilities map specifies an eligibility for a particular SLI for the given instance. The SLI key in the name must be a valid SLI name specified in the Eligibility Exporter binary flags otherwise an error will be emitted by Eligibility Exporter and the oncaller will be alerted. If an SLI has been defined in the binary flags but the eligibilities map does not contain it, the corresponding SLI time series will not be emitted by the Eligibility Exporter. This ensures a smooth rollout and compatibility between the data produced by different versions of the Eligibility Exporters. If eligibilities map contains a key for an SLI which has not been declared in the binary flags, there will be an error message emitted in the Eligibility Exporter log and the metric for the SLI in question will not be emitted.
   * @return eligibilities
   */
  @javax.annotation.Nullable
  public Map<String, SloEligibility> getEligibilities() {
    return eligibilities;
  }

  public void setEligibilities(@javax.annotation.Nullable Map<String, SloEligibility> eligibilities) {
    this.eligibilities = eligibilities;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerSliSloEligibility perSliSloEligibility = (PerSliSloEligibility) o;
    return Objects.equals(this.eligibilities, perSliSloEligibility.eligibilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eligibilities);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerSliSloEligibility {\n");
    sb.append("    eligibilities: ").append(toIndentedString(eligibilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("eligibilities"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PerSliSloEligibility
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PerSliSloEligibility.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PerSliSloEligibility is not found in the empty JSON string", PerSliSloEligibility.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PerSliSloEligibility.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PerSliSloEligibility` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PerSliSloEligibility.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PerSliSloEligibility' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PerSliSloEligibility> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PerSliSloEligibility.class));

       return (TypeAdapter<T>) new TypeAdapter<PerSliSloEligibility>() {
           @Override
           public void write(JsonWriter out, PerSliSloEligibility value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PerSliSloEligibility read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PerSliSloEligibility given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PerSliSloEligibility
   * @throws IOException if the JSON string is invalid with respect to PerSliSloEligibility
   */
  public static PerSliSloEligibility fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PerSliSloEligibility.class);
  }

  /**
   * Convert an instance of PerSliSloEligibility to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

